#!/usr/bin/env bash
# Claude Light installer — macOS
# Run from the claude_light directory:
#   bash install_macos.sh
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

info()  { echo -e "${GREEN}[install]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}   $*"; }
error() { echo -e "${RED}[error]${NC}  $*" >&2; exit 1; }
step()  { echo -e "\n${BOLD}$*${NC}"; }

# ── Detect Apple Silicon vs Intel ───────────────────────────────────────────
ARCH=$(uname -m)
if [[ "$ARCH" == "arm64" ]]; then
    BREW_PREFIX="/opt/homebrew"
    info "Detected Apple Silicon (arm64)"
else
    BREW_PREFIX="/usr/local"
    info "Detected Intel (x86_64)"
fi

# ── Homebrew ─────────────────────────────────────────────────────────────────
step "Checking Homebrew..."
if ! command -v brew &>/dev/null; then
    warn "Homebrew not found."
    echo "  Homebrew is the recommended way to install Python on macOS."
    echo "  Install it from https://brew.sh or run:"
    echo '    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
    echo ""
    echo "  Continuing without Homebrew — will try system Python..."
else
    info "Homebrew found at $(brew --prefix)"
fi

# ── Python ───────────────────────────────────────────────────────────────────
step "Locating Python 3.9+..."

PYTHON=""

# Prefer Homebrew Python (more recent, not "externally managed" in the same way)
for candidate in \
    "$BREW_PREFIX/bin/python3.13" \
    "$BREW_PREFIX/bin/python3.12" \
    "$BREW_PREFIX/bin/python3.11" \
    "$BREW_PREFIX/bin/python3.10" \
    "$BREW_PREFIX/bin/python3.9" \
    "$BREW_PREFIX/bin/python3" \
    python3 \
    python; do
    if command -v "$candidate" &>/dev/null 2>&1; then
        if "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3,9) else 1)' 2>/dev/null; then
            PYTHON="$candidate"
            break
        fi
    fi
done

if [[ -z "$PYTHON" ]]; then
    if command -v brew &>/dev/null; then
        info "Installing Python via Homebrew..."
        brew install python@3.11
        PYTHON="$BREW_PREFIX/bin/python3.11"
    else
        error "Python 3.9+ not found and Homebrew is not available. Install from https://python.org"
    fi
fi

info "Using $("$PYTHON" --version) at $(command -v "$PYTHON")"

# ── Virtual environment (recommended on macOS 13+ / PEP 668) ─────────────────
step "Setting up virtual environment..."

VENV_DIR="$(pwd)/.venv"
if [[ -d "$VENV_DIR" ]]; then
    info "Virtual environment already exists at $VENV_DIR"
else
    "$PYTHON" -m venv "$VENV_DIR"
    info "Created virtual environment at $VENV_DIR"
fi

PYTHON="$VENV_DIR/bin/python"
PIP="$VENV_DIR/bin/pip"

"$PIP" install --upgrade pip --quiet

# ── Required packages ─────────────────────────────────────────────────────────
step "Installing required packages (sentence-transformers pulls PyTorch ~1.5 GB on first run)..."
"$PIP" install --upgrade \
    "sentence-transformers>=5.3.0" \
    "numpy>=2.4.3" \
    "watchdog>=6.0.0" \
    "anthropic>=0.86.0" \
    "prompt_toolkit>=3.0.52"

# ── Optional packages ─────────────────────────────────────────────────────────
step "Installing optional packages (tree-sitter, rich, einops)..."
"$PIP" install --upgrade \
    "tree-sitter>=0.25.2" \
    "tree-sitter-java>=0.23.5" \
    "tree-sitter-python>=0.25.0" \
    "tree-sitter-go>=0.25.0" \
    "tree-sitter-rust>=0.24.1" \
    "tree-sitter-javascript>=0.25.0" \
    "tree-sitter-typescript>=0.23.2" \
    "rich>=14.3.3" \
    "einops>=0.8.2" \
    || warn "Some optional packages failed — the tool still works, with reduced functionality."

# ── API key ───────────────────────────────────────────────────────────────────
step "Checking API key..."
echo ""
if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
    info "ANTHROPIC_API_KEY is already set in the current shell."
else
    warn "ANTHROPIC_API_KEY is not set."
    echo "  Add it to your shell profile. macOS uses zsh by default:"
    echo ""
    echo "    echo 'export ANTHROPIC_API_KEY=sk-ant-...' >> ~/.zshrc"
    echo "    source ~/.zshrc"
    echo ""
    echo "  If you use bash:"
    echo "    echo 'export ANTHROPIC_API_KEY=sk-ant-...' >> ~/.bash_profile"
    echo ""
    echo "  Or place it in a .env file in your project directory."
fi

# ── Wrapper script ────────────────────────────────────────────────────────────
step "Creating run wrapper..."

WRAPPER="$(pwd)/run.sh"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install_macos.sh — activates the venv and runs claude_light.py
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
source "\$SCRIPT_DIR/.venv/bin/activate"
python "\$SCRIPT_DIR/claude_light.py" "\$@"
EOF
chmod +x "$WRAPPER"
info "Created run.sh wrapper"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
info "Installation complete."
echo ""
echo "  Run from your project root using the venv directly:"
echo "    source $(pwd)/.venv/bin/activate"
echo "    python $(pwd)/claude_light.py"
echo ""
echo "  Or use the wrapper (works from any directory):"
echo "    $(pwd)/run.sh"
echo ""
echo "  One-shot example:"
echo "    $(pwd)/run.sh \"What does main.py do?\""
