name: Generate SBOM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cyclonedx-bom

    - name: Generate SBOM
      run: |
        cyclonedx-py requirements -i requirements.txt -o sbom.json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: sbom
        path: sbom.json

    - name: Upload SBOM to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@e7a8f85e1c674dfb5e0fb21681ebc6063a99a7aa # v2.2.2
      with:
        files: sbom.json
